version: "2" 

services:
  user-db: 
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_DATABASE: user 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./databaseUser/init/:/docker-entrypoint-initdb.d/
      - ./databaseUser/datadir/:/var/lib/mysql
    ports:
      - 3333:3306

  user-back:
    build: 
      context: ./backendUser/
      dockerfile: back.Dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://user-db:3306/user?serverTimezone=UTC
    depends_on:
      - user-db

  user-front:
    build:
      context: ./frontendUser/
      dockerfile: front.Dockerfile
    ports:
      - 3001:3001
    expose:
      - 3001
    depends_on:
      - user-back
